// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyezpnlxqbhpzdjzpldf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5ZXpwbmx4cWJocHpkanpwbGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzM5MDksImV4cCI6MjA3MDAwOTkwOX0.FEYgDkuS2_jPC0Q7B1fr7hANG2uBFEeSiw0obQtWvPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});